"""Agregar boleto_id a UsuarioTable

Revision ID: dd085106b4f1
Revises: 8f30f766c928
Create Date: 2024-06-12 13:04:59.976806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd085106b4f1'
down_revision: Union[str, None] = '8f30f766c928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('boleto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'boletos', ['boleto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'boleto_id')
    # ### end Alembic commands ###
